// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AICommonChatRequest struct {
	Ask string `json:"ask"`
}

type AICommonChatResponse struct {
	Answer string `json:"answer"`
}

type AIRequest struct {
	Ask string `json:"ask"`
}

type AIResponse struct {
	Answer string `json:"answer"`
}

type AIVideoChatRequest struct {
	Ask string `json:"ask"`
}

type AIVideoChatResponse struct {
	Answer string `json:"answer"`
}
