// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type GetTokenRequest struct {
	UserID   string `json:"user_id"`
	UserName string `json:"user_name"`
	Role     string `json:"role"`
}

type GetTokenResponse struct {
	Atoken string `json:"atoken"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Atoken string `json:"atoken"`
	Rtoken string `json:"rtoken"`
}

type RefreshTokenRequest struct {
	Rtoken string `json:"rtoken"`
}

type RefreshTokenResponse struct {
	Atoken string `json:"atoken"`
}

type RegisterRequest struct {
	Email    string `json:"email"`
	Code     string `json:"code"`
	Password string `json:"password"`
	Username string `json:"username"`
	Avatar   string `json:"avatar" gorm:"column:avatar;type:varchar(255);comment:头像URL"`
}

type RegisterResponse struct {
	Atoken string `json:"atoken"`
}

type SendCodeRequest struct {
	Email string `json:"email"`
}

type SendCodeResponse struct {
}
