// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"eino_gozero/apps/AI/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/AIGetUserInfoChat",
				Handler: AIGetUserInfoChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/AIGetVideoChat",
				Handler: AIGetVideoChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/AISendCodeChat",
				Handler: AISendCodeChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/AISendResumeChat",
				Handler: AISendResumeChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/aiAllChat",
				Handler: aiAllChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/aiCommonChat",
				Handler: aiCommonChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/aiVideoChat",
				Handler: aiVideoChatHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/ai"),
	)
}
