// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.9.0
// source: ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AICommonChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ask           string                 `protobuf:"bytes,1,opt,name=Ask,proto3" json:"Ask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AICommonChatRequest) Reset() {
	*x = AICommonChatRequest{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AICommonChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AICommonChatRequest) ProtoMessage() {}

func (x *AICommonChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AICommonChatRequest.ProtoReflect.Descriptor instead.
func (*AICommonChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AICommonChatRequest) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

type AICommonChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=Answer,proto3" json:"Answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AICommonChatResponse) Reset() {
	*x = AICommonChatResponse{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AICommonChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AICommonChatResponse) ProtoMessage() {}

func (x *AICommonChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AICommonChatResponse.ProtoReflect.Descriptor instead.
func (*AICommonChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AICommonChatResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type AIVideoChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ask           string                 `protobuf:"bytes,2,opt,name=Ask,proto3" json:"Ask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIVideoChatRequest) Reset() {
	*x = AIVideoChatRequest{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIVideoChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIVideoChatRequest) ProtoMessage() {}

func (x *AIVideoChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIVideoChatRequest.ProtoReflect.Descriptor instead.
func (*AIVideoChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *AIVideoChatRequest) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

type AIVideoChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=Answer,proto3" json:"Answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIVideoChatResponse) Reset() {
	*x = AIVideoChatResponse{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIVideoChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIVideoChatResponse) ProtoMessage() {}

func (x *AIVideoChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIVideoChatResponse.ProtoReflect.Descriptor instead.
func (*AIVideoChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *AIVideoChatResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type AISendCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ask           string                 `protobuf:"bytes,2,opt,name=Ask,proto3" json:"Ask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AISendCodeRequest) Reset() {
	*x = AISendCodeRequest{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AISendCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AISendCodeRequest) ProtoMessage() {}

func (x *AISendCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AISendCodeRequest.ProtoReflect.Descriptor instead.
func (*AISendCodeRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *AISendCodeRequest) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

type AISendCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=Answer,proto3" json:"Answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AISendCodeResponse) Reset() {
	*x = AISendCodeResponse{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AISendCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AISendCodeResponse) ProtoMessage() {}

func (x *AISendCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AISendCodeResponse.ProtoReflect.Descriptor instead.
func (*AISendCodeResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *AISendCodeResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type AIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ask           string                 `protobuf:"bytes,2,opt,name=Ask,proto3" json:"Ask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIRequest) Reset() {
	*x = AIRequest{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIRequest) ProtoMessage() {}

func (x *AIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIRequest.ProtoReflect.Descriptor instead.
func (*AIRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *AIRequest) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

type AIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=Answer,proto3" json:"Answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIResponse) Reset() {
	*x = AIResponse{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIResponse) ProtoMessage() {}

func (x *AIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIResponse.ProtoReflect.Descriptor instead.
func (*AIResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *AIResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"'\n" +
	"\x13AICommonChatRequest\x12\x10\n" +
	"\x03Ask\x18\x01 \x01(\tR\x03Ask\".\n" +
	"\x14AICommonChatResponse\x12\x16\n" +
	"\x06Answer\x18\x01 \x01(\tR\x06Answer\"&\n" +
	"\x12AIVideoChatRequest\x12\x10\n" +
	"\x03Ask\x18\x02 \x01(\tR\x03Ask\"-\n" +
	"\x13AIVideoChatResponse\x12\x16\n" +
	"\x06Answer\x18\x01 \x01(\tR\x06Answer\"%\n" +
	"\x11AISendCodeRequest\x12\x10\n" +
	"\x03Ask\x18\x02 \x01(\tR\x03Ask\",\n" +
	"\x12AISendCodeResponse\x12\x16\n" +
	"\x06Answer\x18\x01 \x01(\tR\x06Answer\"\x1d\n" +
	"\tAIRequest\x12\x10\n" +
	"\x03Ask\x18\x02 \x01(\tR\x03Ask\"$\n" +
	"\n" +
	"AIResponse\x12\x16\n" +
	"\x06Answer\x18\x01 \x01(\tR\x06Answer2\xf5\x02\n" +
	"\x02ai\x12A\n" +
	"\fAICommonChat\x12\x17.ai.AICommonChatRequest\x1a\x18.ai.AICommonChatResponse\x12>\n" +
	"\vAIVideoChat\x12\x16.ai.AIVideoChatRequest\x1a\x17.ai.AIVideoChatResponse\x12;\n" +
	"\n" +
	"AISendCode\x12\x15.ai.AISendCodeRequest\x1a\x16.ai.AISendCodeResponse\x12-\n" +
	"\fAISendResume\x12\r.ai.AIRequest\x1a\x0e.ai.AIResponse\x12.\n" +
	"\rAIGetUserInfo\x12\r.ai.AIRequest\x1a\x0e.ai.AIResponse\x12+\n" +
	"\n" +
	"AIGetVideo\x12\r.ai.AIRequest\x1a\x0e.ai.AIResponse\x12#\n" +
	"\x02AI\x12\r.ai.AIRequest\x1a\x0e.ai.AIResponseB\x06Z\x04./aib\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ai_proto_goTypes = []any{
	(*AICommonChatRequest)(nil),  // 0: ai.AICommonChatRequest
	(*AICommonChatResponse)(nil), // 1: ai.AICommonChatResponse
	(*AIVideoChatRequest)(nil),   // 2: ai.AIVideoChatRequest
	(*AIVideoChatResponse)(nil),  // 3: ai.AIVideoChatResponse
	(*AISendCodeRequest)(nil),    // 4: ai.AISendCodeRequest
	(*AISendCodeResponse)(nil),   // 5: ai.AISendCodeResponse
	(*AIRequest)(nil),            // 6: ai.AIRequest
	(*AIResponse)(nil),           // 7: ai.AIResponse
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: ai.ai.AICommonChat:input_type -> ai.AICommonChatRequest
	2, // 1: ai.ai.AIVideoChat:input_type -> ai.AIVideoChatRequest
	4, // 2: ai.ai.AISendCode:input_type -> ai.AISendCodeRequest
	6, // 3: ai.ai.AISendResume:input_type -> ai.AIRequest
	6, // 4: ai.ai.AIGetUserInfo:input_type -> ai.AIRequest
	6, // 5: ai.ai.AIGetVideo:input_type -> ai.AIRequest
	6, // 6: ai.ai.AI:input_type -> ai.AIRequest
	1, // 7: ai.ai.AICommonChat:output_type -> ai.AICommonChatResponse
	3, // 8: ai.ai.AIVideoChat:output_type -> ai.AIVideoChatResponse
	5, // 9: ai.ai.AISendCode:output_type -> ai.AISendCodeResponse
	7, // 10: ai.ai.AISendResume:output_type -> ai.AIResponse
	7, // 11: ai.ai.AIGetUserInfo:output_type -> ai.AIResponse
	7, // 12: ai.ai.AIGetVideo:output_type -> ai.AIResponse
	7, // 13: ai.ai.AI:output_type -> ai.AIResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
